### ISSUE TITLE
Other bad data checks

### ISSUE THREAD

**Issue by trentonbrochill** [Remiles45/ROS_Visualizer_GUI#4]
https://github.com/Remiles45/ROS_Visualizer_GUI/blob/c05c313ca19a52106710fe3b1236f2182e01229d/turtlebot_gui/src/ViewerWidget.cpp#L88

I like checking if empty here, but may also want to check other hallmarks of bad data. 
1. Only 1 point in the scan
2. NaN in scan

**Comment by Remiles45** [comment]
NaN is now being handled in the data filtering. Added ros warning if empty data received. (depending on sensor, a 1 point scan could be valid. maybe future work could be to add a setting in the GUI that can let the user set a threshold for throwing out a too-few datapoint scan but for now leaving it as just checking if empty after all NaN and inf values are removed.

**Comment by trentonbrochill** [comment]
but what does the qt scatter plot do with one point? I think they choose axes based on the data, so single point might be undefined behavior. (I haven't googled it)

**Comment by Remiles45** [comment]
the answer seems to be a minimum of 3 points is required. So now I check if the size is < 3.
